const express = require('express')
const StaffCtrl = require('../controllers/staff.ctrl')
const auth = require('../middlewares/auth.middleware')
const permission = require('../middlewares/permission.middleware')
const {ROLE_LABLE } = require('../models/constants')

const router = express.Router()
router.post('/UserForm',auth([ROLE_LABLE.BRANCH_LABLE]), StaffCtrl.createUserBranch)
router.post('/UserFormInstitute',auth([ROLE_LABLE.INSTITUTE_LABLE]), StaffCtrl.createUserInstitute)
router.get('/InstituteUser',permission("M3",[1]),auth([ROLE_LABLE.INSTITUTE_LABLE]), StaffCtrl.getUserInstitute)  
router.get('/User',permission("M3",[1]),auth(Object.values(ROLE_LABLE)), StaffCtrl.getUsers)
router.get('/User/:id',permission("M3",[1]),auth(Object.values(ROLE_LABLE)), StaffCtrl.getUser)
router.get('/UserRolesBranch',auth(Object.values(ROLE_LABLE)), StaffCtrl.userRolesDdrBranch)
router.get('/UserRolesIstitute',auth(Object.values(ROLE_LABLE)), StaffCtrl.userRolesDdrInstitute)
router.delete('/staff/:id',auth(Object.values(ROLE_LABLE)), StaffCtrl.deleteUser)
module.exports = router